<?php

return [
    'enabled' => true,

    'options' => [
        'dpi' => env('DOMPDF_DPI', 96),
        'defaultMediaType' => env('DOMPDF_MEDIA_TYPE', 'screen'),
        'defaultPaperSize' => env('DOMPDF_DEFAULT_PAPER_SIZE', 'a4'),
        'defaultFont' => env('DOMPDF_DEFAULT_FONT', 'DejaVu Sans'),
        'direction' => env('DOMPDF_DIRECTION', 'ltr'),
        'isHtml5ParserEnabled' => env('DOMPDF_HTML5_PARSER', false),
        'isPhpEnabled' => env('DOMPDF_PHP_ENABLED', false),
        'isRemoteEnabled' => env('DOMPDF_REMOTE_ENABLED', true),
        'isJavascriptEnabled' => env('DOMPDF_JAVASCRIPT_ENABLED', true),
        'isActiveFormXObjects' => env('DOMPDF_ACTIVE_FORM_X_OBJECTS', false),
        'isFontSubsettingEnabled' => env('DOMPDF_FONT_SUBSETTING', false),
        'debugKeepTemp' => env('DOMPDF_DEBUG_KEEP_TEMP', false),
        'debugPdf' => env('DOMPDF_DEBUG_PDF', false),
        'debugLayout' => env('DOMPDF_DEBUG_LAYOUT', false),
        'debugLayoutLines' => env('DOMPDF_DEBUG_LAYOUT_LINES', true),
        'debugLayoutBlocks' => env('DOMPDF_DEBUG_LAYOUT_BLOCKS', true),
        'debugLayoutInline' => env('DOMPDF_DEBUG_LAYOUT_INLINE', true),
        'pdfBackend' => env('DOMPDF_PDF_BACKEND', 'CPDF'),
        'pdflibVersion' => env('DOMPDF_PDFLIB_VERSION', ''),
        'adminEmail' => env('DOMPDF_ADMIN_EMAIL', 'admin@example.com'),
        'buyLicenseUrl' => env('DOMPDF_BUY_LICENSE_URL', 'http://www.digitalsmarties.com'),
        'logOutputFile' => env('DOMPDF_LOG_OUTPUT_FILE', null),
        'tempDir' => env('DOMPDF_TEMP_DIR', sys_get_temp_dir()),
        'fontDir' => env('DOMPDF_FONT_DIR', storage_path('fonts')),
        'fontCache' => env('DOMPDF_FONT_CACHE', storage_path('fonts')),
        'chroot' => env('DOMPDF_CHROOT', realpath(base_path())),
        'allowedProtocols' => env('DOMPDF_ALLOWED_PROTOCOLS', ['http', 'https', 'file', 'ftp']),
        'allowedRemoteHosts' => env('DOMPDF_ALLOWED_REMOTE_HOSTS', []),
        'allowFrames' => env('DOMPDF_ALLOW_FRAMES', true),
        'allowExternalFiles' => env('DOMPDF_ALLOW_EXTERNAL_FILES', true),
        'blankMarginPercent' => env('DOMPDF_BLANK_MARGIN_PERCENT', 0.1),
        'tableLayout' => env('DOMPDF_TABLE_LAYOUT', 'auto'),
        'tableCellMargin' => env('DOMPDF_TABLE_CELL_MARGIN', 0),
        'defaultViewport' => ['x' => 0, 'y' => 0, 'w' => 800, 'h' => 600],
        'useUnicodeUTF8Encoding' => env('DOMPDF_USE_UNICODE_UTF8_ENCODING', true),
    ],

    'defines' => [
        'DOMPDF_ENABLE_AUTOLOADER' => env('DOMPDF_ENABLE_AUTOLOADER', true),
        'DOMPDF_ENABLE_REMOTE' => env('DOMPDF_ENABLE_REMOTE', true),
        'DOMPDF_UNICODE_ENABLED' => env('DOMPDF_UNICODE_ENABLED', true),
    ],
];
